### ISSUE TITLE
If window height has been changed by dragging, scratch should use new window height the next time

### ISSUE THREAD

**Issue by sagarjauhari** [mtth/scratch.vim#14]

**Comment by mtth** [comment]
This seems to be a rather minor use-case. Once you've dragged the window to a size you like, set that value as `g:scratch_height` once and that's it (or use a float to keep the same proportion irrespective of the overall size, the scratch window will be resized appropriately when you next open it). If you think this is worth it, feel free to take a stab at it yourself, I'll be happy to review it.
