### ISSUE TITLE
Toggle Scratch Window?

### ISSUE THREAD

**Issue by stockninja** [mtth/scratch.vim#17]
Is it possible to toggle the scratch window?

What I mean by this is:
- I'm typing away and I want to open the scratch window but not have my cursor move to the scratch window. I look at the scratch window, a few moments pass, then I want to close it without moving my cursor to the window and hitting `:q`.

Is there a way I can achieve this?

Thanks

**Comment by mtth** [comment]
3f969e6ce68ca37c3ea66d7e4dcac1f09a2232dc adds a [`:ScratchPreview`](https://github.com/mtth/scratch.vim/blob/master/doc/scratch.txt#L65) command which should do what you want :). Let me know if you had something else in mind.

**Comment by jdsutherland** [comment]
I think making `:Scratch` close the scratch buffer when called from the scratch buffer would be ideal behavior. I'll submit a PR if you're interested.

`:ScratchPreview` is useful if you want to reference the scratch while making changes in other buffers but I find myself rarely doing this; I mostly want to add or reference the scratch and keeping this plugin to a single toggle mapping for simplicity.
