### ISSUE TITLE
Open the scratch window into a system command

### ISSUE THREAD

**Issue by andreiglingeanu** [mtth/scratch.vim#20]
I've set my filetype to `javascript` and tried to load execute the scratch window with node, like this: `!node %`. It tried to open the `__Scratch__` file. Is there a way to make it open the file specified in `g:scratch_persistence_file`?

Let me know if I can help with a pull request, I don't know where to look for a solution.

**Comment by mtth** [comment]
Hey, thanks for the offer! You should already be able to do what you want by changing your command to:
```viml
:execute '!node ' . g:scratch_persistence_file
```

In most cases, you can also run it without having a backing underlying file at all (streaming the file via `stdin` instead):
```viml
:w !node
```

Does either solution address your use-case?

**Comment by andreiglingeanu** [comment]
@mtth Huh, didn't know about the second way of doing it.

Thank you, that looks like a solution to me!
