### ISSUE TITLE
Add an option to open the scratch in normal mode

### ISSUE THREAD

**Issue by fvictorio** [mtth/scratch.vim#21]
I'm using scratch.vim as a buffer for to-do items, so I find myself opening it and going straight to normal mode to navigate the items and mark them as done or move them around.

It would be nice to be able to configure scratch to use normal mode by default instead of insert mode.

I'm willing to send a PR if you think this would be a useful feature.

Thanks!

**Comment by mtth** [comment]
The `:Scratch` command opens the scratch buffer and puts you in normal mode, are you looking for something else?

**Comment by fvictorio** [comment]
Oh, sorry. I just assumed that `gs` was a map for `:Scratch<cr>` :disappointed: My bad. Thanks!

**Comment by dubiousdavid** [comment]
Thought I would leave this here for posterity. My scratch mappings:
```
let g:scratch_no_mappings = 1
nmap <leader>si <plug>(scratch-insert-reuse)
xmap <leader>si <plug>(scratch-selection-reuse)
nmap <leader>sp :ScratchPreview<CR>
nmap <leader>se :Scratch<CR>
```
Where si is short for scratch insert, sp is short for scratch preview, and se is short for scratch edit.
