### ISSUE TITLE
Feature Request: Ability to source scratch file

### ISSUE THREAD

**Issue by amadeus** [mtth/scratch.vim#23]
Not quite sure how this would look, but sometimes it would be nice to write a lil vim script in a scratch buffer and source it.

Perhaps a command like `:ScratchSource` which would write to the persistence file and immediately source it?

**Comment by mtth** [comment]
I think this would be best implemented as a standalone command which sources the current buffer. You'd just need to call it from the scratch buffer. For convenience you could have the command also close the buffer.

**Comment by mtth** [comment]
Looks like there's already a nice [wiki page](http://vim.wikia.com/wiki/Source_current_file_when_editing_a_script) for this, so I'll close this for now.
