### ISSUE TITLE
Support setting file type in scratch window

### ISSUE THREAD

**Issue by jkramer** [mtth/scratch.vim#29]
Support setting/detecting the file type in the scratch window, so if for example I set `g:scratch_persistence_file` to `~/.scratch.md`, it would be nice to have markdown syntax enabled in the scratch window. Or alternatively introduce a variable like `g:scratch_syntax` so I can set the syntax manually in my `.vimrc`.

**Comment by mtth** [comment]
As mentioned in the PR (https://github.com/mtth/scratch.vim/pull/30#issuecomment-417541856), this is already available via the `g:scratch_filetype` option.
