### ISSUE TITLE
Default :Scratch windows to a certain programming language format?

### ISSUE THREAD

**Issue by mcandre** [mtth/scratch.vim#3]
scratch.vim is really cool! I'd love to use it to pop up a quick "markdown" window, since I spend a lot of time reporting bugs.

How could I configure my `~/.vimrc` so that `:Scratch` opens in markdown format by default?

**Comment by kminh** [comment]
Maybe we can improve this further by prompting for filetype when creating a new scratch buffer (not on reuse)? Perhaps something like `:ScratchType`.
