### ISSUE TITLE
Feature Request - Floating Window Support

### ISSUE THREAD

**Issue by weilbith** [mtth/scratch.vim#34]
_NeoVim_ has introduced floating windows a while ago. It would be awesome if this plugin would offer a configuration option to make use of this? The height and width options could then be reused for this window and must not be exclusive anymore. What do you think?

**Comment by mtth** [comment]
Hi @weilbith, how much NeoVim-specific work would this require?

**Comment by weilbith** [comment]
Yeah, that is the point. _NeoVim_ and _Vim_ have different APIs for their floating windows. Not sure how other plugins handle this. :thinking:

**Comment by mtth** [comment]
I am not familiar with this either but am happy to review a PR and merge it if the added complexity is reasonable.

**Comment by weilbith** [comment]
I'm just going through the list open issues by me.
I don't use this plugin atm. and as nobody else seem to have further interest I just close it for the moment. If it gets attention again it could be re-opened at any time. :smiley:
