### ISSUE TITLE
Allowing for custom name of the scratch buffer

### ISSUE THREAD

**Issue by Narice** [mtth/scratch.vim#35]
For now, the scratch buffer is named \_\_Scratch\_\_
I would like to change that to gain support for the vim-markdown plugin by renaming it scratch.md for example.
I've seen in the code that it might be easily implementable if the name of a scratch buffer doesn't always have to be equal to \_\_Scratch\_\_
I will try to do a pull request as soon as possible.
Also, I might help you on other issues as I really like the concept of a scratch window for example for todo list perposes (which is why I wanted markdown in the first place)

**Comment by mtth** [comment]
Hi @Narice,

> I would like to change that to gain support for the vim-markdown plugin by renaming it scratch.md for example.

Can you get the features you need by setting the buffer's `filetype`? ([There is an option for this.](https://github.com/mtth/scratch.vim/issues/3))
