### ISSUE TITLE
When installing with vundle, it requests my github password

### ISSUE THREAD

**Issue by dgmstuart** [mtth/scratch.vim#40]
This is unexpected: Vundle doesn't do this with other plugins. I'm not keen to give my password to a third party plugin 😅

**Comment by mtth** [comment]
I'm not sure how this is possible, the repo is public (and hasn't changed in a long time). I'm fairly confident this is an issue with your setup. Feel free reopen providing details if you think otherwise.

**Comment by dgmstuart** [comment]
Quite right - not sure how that happened. Successfully installed now - thank you for taking the time to answer.
